#!/bin/sh

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi

# nitrogen --restore
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr

# if [ -s ~/.Xmodmap ]; then
    # xmodmap ~/.Xmodmap
# fi

#xbindkeys
#compton --opacity-rule 80:'window_type = "dock" && class_g = "i3bar"' -b
#compton --opacity-rule 80:'name *= "[i3 con]"' --opacity-rule 80:'window_type = "dock" && class_g = "i3bar"' --backend glx --vsync opengl-oml -b
#export GTK_MODULES=winmenu
#export http_proxy=http://172.16.16.1:8080
#export no_proxy="127.0.0.1,localhost"

# xset m <ускорение> <порог чувствительности>
#xset m 3/2 0 &

# xset r rate 200 30
xset r rate 200 40

urxvtd -q -o -f

VBoxClient --display
# VBoxClient --clipboard
VBoxClient --seamless

#parcellite -d &

#xbanish &

exec i3 -V >> ~/.i3/i3log 2>&1
